worldpostcodes/users/urls.py
from django.urls import path

from users.views import (
    LoginView, LogoutView, PasswordResetView,
    PasswordResetCompleteView, PasswordResetDoneView,
    PasswordResetConfirmView, AccountActivationSent, activate, SignupTypeView,SignupView, PendingActivationView
)


urlpatterns = [
    path('signup/type/', SignupTypeView.as_view(), name='signup-type'),
    path('signup/', SignupView.as_view(), name='signup'),
#     path('login/', LoginView.as_view(), name='login'),
#     path('logout/', LogoutView.as_view(), name='logout'),
    path('password_reset', PasswordResetView.as_view(),
         name='password_reset'),
    path('password_reset/done', PasswordResetDoneView.as_view(),
         name='password_reset_done'),
    path('reset/<str:uidb64>/<str:token>/',
         PasswordResetConfirmView.as_view(),
         name='password_reset_confirm'),
    path('reset/done', PasswordResetCompleteView.as_view(),
         name='password_reset_complete'),
    path('account_activation_sent', AccountActivationSent.as_view(),
         name='account_activation_sent'),
    path('pending/activation/', PendingActivationView.as_view(),
         name='pending_activation'),
    path('activate/<str:uidb64>/<str:token>/', activate, name='activate'),
]

worldpostcodes/worldpostcodes/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from core.utils import delete_item, model_order
from invitations.functions import activate_invite



from .views import IndexView, ManageView

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('postalcodes/', include('postalcodes.urls',namespace='postalcodes')),
    path('geonames/', include('geonames.urls',namespace='geonames')),
    path('activate/invitation/<str:uidb64>/<str:token>/', activate_invite, name='activate-invite'),
    path('delete/item/', delete_item, name='delete-item'),
    path('model/order/', model_order, name='model-order'),
    path('manage/', ManageView.as_view(), name='manage'),
    path('accounts/',include('django.contrib.auth.urls')),
    path('users/', include('users.urls')),
    path('companies/', include('companies.urls',namespace='companies')),
    path('invitations/', include('invitations.urls',namespace='invitations')),
    path('profiles/', include('profiles.urls')),
    path('admin/', admin.site.urls),
    path('pages/', include('django.contrib.flatpages.urls')),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    try:
        import debug_toolbar
        urlpatterns += [
            path('__debug__', include(debug_toolbar.urls)),
        ]
    except ImportError:
        pass

worldpostcodes/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
<head>
    <meta charset="utf-8">
    <title>{% block page_title %}{% endblock %}</title>
    <link href="/static/lib/bootstrap-5.3.3-dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="/static/lib/bootstrap-icons-1.11.3/font/bootstrap-icons.css">
    <link href="/static/lib/select2/select2.min.css" rel="stylesheet"/>
    <script src="/static/js/jquery-3.7.1.min.js"></script>
    <script src="/static/js/jquery.formset.js"></script>
    <script src="/static/lib/select2/select2.min.js"></script>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="/static/css/site.css">

    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.9.4/dist/leaflet.css"/>

    <link href="/static/lib/jquery-nice-select-1.1.0/css/nice-select.css" rel="stylesheet"/>
    <script src="/static/lib/jquery-nice-select-1.1.0/js/jquery.nice-select.min.js"></script>


    <link href="/static/lib/select2/select2.min.css" rel="stylesheet"/>
    <script src="/static/lib/select2/select2.min.js"></script>

    <script src="https://unpkg.com/leaflet@1.9.4/dist/leaflet.js"></script>

    <link rel="stylesheet" href="https://unpkg.com/leaflet.markercluster@1.5.3/dist/MarkerCluster.css"/>
    <script src="https://unpkg.com/leaflet.markercluster@1.5.3/dist/leaflet.markercluster.js"></script>

    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.9.4/dist/leaflet.css"/>
    <link rel="stylesheet" href="https://unpkg.com/leaflet.markercluster@1.5.3/dist/MarkerCluster.css"/>


    <script src="https://unpkg.com/leaflet@1.9.4/dist/leaflet.js"></script>
    <script src="https://unpkg.com/leaflet.markercluster@1.5.3/dist/leaflet.markercluster.js"></script>

    <link rel="stylesheet" href="https://unpkg.com/leaflet.markercluster@1.5.3/dist/MarkerCluster.css"/>
    <script src="https://unpkg.com/leaflet.markercluster@1.5.3/dist/leaflet.markercluster.js"></script>


    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.9.4/dist/leaflet.css"/>
    <link rel="stylesheet" href="https://unpkg.com/leaflet.markercluster@1.5.3/dist/MarkerCluster.css"/>
    <link rel="stylesheet" href="https://unpkg.com/leaflet.markercluster@1.5.3/dist/MarkerCluster.Default.css"/>


    <!-- Required JS -->
    <script src="https://unpkg.com/leaflet@1.9.4/dist/leaflet.js"></script>
    <script src="https://unpkg.com/leaflet.markercluster@1.5.3/dist/leaflet.markercluster.js"></script>


    <style>#map {
        height: 90vh;
    }

    .nice-select {
        z-index: 10000 !important;
        position: relative;
    }

    .nice-select .list {
        z-index: 10001 !important;
    }

    .nice-select .list {
        max-height: 200px; /* Adjust this as needed */
        min-height: 100px; /* Optional: Ensures it's not too short */
        overflow-y: auto; /* Enables vertical scrolling */
    }

    .nice-select .list::-webkit-scrollbar {
        width: 6px;
    }

    .nice-select .list::-webkit-scrollbar-thumb {
        background-color: #ccc;
        border-radius: 3px;
    }


    .select2-container--default .select2-selection--single {
        height: 46px !important;
        padding: 10px 16px;
        font-size: 18px;
        line-height: 1.33;
        border-radius: 6px;
    }

    .select2-container--default .select2-selection--single .select2-selection__arrow b {
        top: 85% !important;
    }

    .select2-container--default .select2-selection--single .select2-selection__rendered {
        line-height: 26px !important;
    }

    .select2-container--default .select2-selection--single {
        border: 1px solid #CCC !important;
        box-shadow: 0px 1px 1px rgba(0, 0, 0, 0.075) inset;
        transition: border-color 0.15s ease-in-out 0s, box-shadow 0.15s ease-in-out 0s;
    }


    </style>


</head>
<body id="{% block body_id %}{% endblock %}" class="{% block body_class %}{% endblock %}"
        {% block body_attrs %}{% endblock %}>
{% include 'navbar.html' %}
<main class="container">
    <div class="row py-2">
        <div class="col-12">
            {% include 'messages.html' %}
        </div>
    </div>
    <div class="row py-2">
        <div class="col-12">
            {% block content %}{% endblock %}
        </div>
    </div>
</main>

<script src="/static/js/popper.min.js"></script>
<script src="/static/lib/bootstrap-5.3.3-dist/js/bootstrap.min.js"></script>
<script src="/static/js/django_ajax.js"></script>
<script src="/static/js/site_.js"></script>


<script>
    'use strict';
    $(document).ready(function () {
        $('.spinner-border').hide();
        // Show loader when request starts
        $(document).ajaxStart(function () {
            $('.spinner-border').show();
        });

        // Hide loader when request completes
        $(document).ajaxStop(function () {
            $('.spinner-border').hide();
        });
    });
</script>


{% block scripts %}{% endblock scripts %}
</body>
</html>

worldpostcodes/templates/form_email.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional //EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
{% load static %}
{% load i18n %}
<html>
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <title></title>
  </head>

  <body style="margin: 0; padding: 0; background-color: #f6f6f6;">
    <table cellpadding="0" cellspacing="0" width="100%">
      <table class="table">
        <tr class="">
          {% if user %}
            <td>{{user}}</td>
          {% endif %}

          <td>{{title}}</td>

      </table>
    </table>

  </body>
</html>

worldpostcodes/templates/index.html
{% extends 'base.html' %}

{% block content %}
index
{% endblock %}

worldpostcodes/templates/messages.html
{% for message in messages %}
  <div class="alert {{ message.tags }} alert-dismissible fade show" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    {{ message }}
  </div>
{% endfor %}

worldpostcodes/templates/navbar.html
{% url 'index' as index_url %}
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="{{index_url}}">Navbar</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link {% if request.path == index_url %}active {% endif %}" aria-current="page" href="{{index_url}}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'postalcodes:index' %}">Postal Codes</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'geonames:index' %}">Geo names</a>
        </li>
      </ul>
      <ul class="navbar-nav">
        {% if not request.user.is_anonymous %}
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            <i class="bi bi-person-fill"></i>{{request.user}}
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="{% url 'manage' %}">Manage</a></li>
            <li><a class="dropdown-item" href="{% url 'profile-detail' request.user.profile.pk %}">My profile</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><form action="{% url 'logout' %}" method="post">{% csrf_token %} <button type="submit" class="dropdown-item">Logout</button></form></li>
          </ul>
        </li>
        {% else %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'signup-type' %}">Signup</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'login' %}">Login</a>
        </li>
        {% endif %}
      </ul>
    </div>
  </div>
</nav>

worldpostcodes/templates/pagination.html
{% if is_paginated %}
<nav aria-label="Page navigation example">
  <ul class="pagination justify-content-center">
    {% if page_obj.number != 1  %}
    <li class="page-item"><a class="page-link" href="?page={{ 1 }}{{query_string}}">First Page</a></li>
    {% endif %}
    {% if page_obj.has_previous %}
      <li class="page-item"><a class="page-link"  href="?page={{ page_obj.previous_page_number }}{{query_string}}">&laquo;</a></li>
    {% else %}
      <li class="page-item disabled"><a class="page-link" href="#" tabindex="-1" aria-disabled="true">&laquo;</a></li>
    {% endif %}
    {% for i in pages %}
      {% if page_obj.number == i %}
        <li class="page-item active"><a class="page-link" href="#">{{i}}</a></li>
      {% else %}
        <li class="page-item"><a class="page-link"  href="?page={{ i }}{{query_string}}">{{ i }}</a></li>
      {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
      <li class="page-item"><a class="page-link"  href="?page={{ page_obj.next_page_number }}{{query_string}}">&raquo;</a></li>
    {% else %}
      <li class="page-item disabled"><a class="page-link" href="#" tabindex="-1" aria-disabled="true">&raquo;</a></li>
    {% endif %}
    {% if page_obj.number != page_obj.paginator.num_pages %}
    <li class="page-item"><a class="page-link" href="?page={{ page_obj.paginator.num_pages }}{{query_string}}">Last Page</a></li>
    {% endif %}
  </ul>
</nav>
{% endif %}