worldpostcodes/companies/urls.py
from django.urls import path, include


from companies import views,functions

app_name = 'companies'


urlpatterns = [
    path('',views.CompanyListView.as_view(),name='company_list'),
    path('create/',views.CompanyCreateView.as_view(),name='company_add'),
    path('detail/<int:pk>/',views.CompanyDetailView.as_view(),name='company_view'),
    path('update/<int:pk>/',views.CompanyUpdateView.as_view(),name='company_change'),
    path('delete/<int:pk>/',views.CompanyDeleteView.as_view(),name='company_delete'),

    path('activate/profile/<int:company_id>/int<user_id>/',functions.activate_company_profile,name='activate-profile'),
    path('remove/profile/<int:company_id>/int<profile_id>/',functions.remove_company_profile,name='remove-profile'),
    path('assign-permissions/<int:company_id>/<int:user_id>/', views.assign_permissions, name='assign_permissions'),
    path('sb/', functions.get_company_for_sb, name='sb-companies'),
]

worldpostcodes/invitations/urls.py
from django.urls import path, include


from invitations import views,functions

app_name = 'invitations'


urlpatterns = [
    path('',views.InvitationListView.as_view(),name='invitation_list'),
    path('create/',views.InvitationCreateView.as_view(),name='invitation_add'),
    path('detail/<int:pk>/',views.InvitationDetailView.as_view(),name='invitation_view'),
    path('update/<int:pk>/',views.InvitationUpdateView.as_view(),name='invitation_change'),
    path('delete/<int:pk>/',views.InvitationDeleteView.as_view(),name='invitation_delete'),

    path('resend/invitation/<int:invitation_id>/',functions.resend_invitation,name='resend-invitation'),

]

worldpostcodes/users/urls.py
from django.urls import path

from users.views import (
    LoginView, LogoutView, PasswordResetView,
    PasswordResetCompleteView, PasswordResetDoneView,
    PasswordResetConfirmView, AccountActivationSent, activate, SignupTypeView,SignupView, PendingActivationView
)


urlpatterns = [
    path('signup/type/', SignupTypeView.as_view(), name='signup-type'),
    path('signup/', SignupView.as_view(), name='signup'),
#     path('login/', LoginView.as_view(), name='login'),
#     path('logout/', LogoutView.as_view(), name='logout'),
    path('password_reset', PasswordResetView.as_view(),
         name='password_reset'),
    path('password_reset/done', PasswordResetDoneView.as_view(),
         name='password_reset_done'),
    path('reset/<str:uidb64>/<str:token>/',
         PasswordResetConfirmView.as_view(),
         name='password_reset_confirm'),
    path('reset/done', PasswordResetCompleteView.as_view(),
         name='password_reset_complete'),
    path('account_activation_sent', AccountActivationSent.as_view(),
         name='account_activation_sent'),
    path('pending/activation/', PendingActivationView.as_view(),
         name='pending_activation'),
    path('activate/<str:uidb64>/<str:token>/', activate, name='activate'),
]

worldpostcodes/worldpostcodes/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from core.utils import delete_item, model_order
from invitations.functions import activate_invite



from .views import IndexView, ManageView

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('postalcodes/', include('postalcodes.urls',namespace='postalcodes')),
    path('geonames/', include('geonames.urls',namespace='geonames')),
    path('activate/invitation/<str:uidb64>/<str:token>/', activate_invite, name='activate-invite'),
    path('delete/item/', delete_item, name='delete-item'),
    path('model/order/', model_order, name='model-order'),
    path('manage/', ManageView.as_view(), name='manage'),
    path('accounts/',include('django.contrib.auth.urls')),
    path('users/', include('users.urls')),
    path('companies/', include('companies.urls',namespace='companies')),
    path('invitations/', include('invitations.urls',namespace='invitations')),
    path('profiles/', include('profiles.urls')),
    path('admin/', admin.site.urls),
    path('pages/', include('django.contrib.flatpages.urls')),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    try:
        import debug_toolbar
        urlpatterns += [
            path('__debug__', include(debug_toolbar.urls)),
        ]
    except ImportError:
        pass

worldpostcodes/templates/includes/footer.html
<footer class="bg-white rounded shadow p-5 mb-4 mt-4">
    <div class="row">
        <div class="col-12 col-md-4 col-xl-6 mb-4 mb-md-0">
            <p class="mb-0 text-center text-lg-start">
                &copy; <a class="text-primary fw-normal" href="https://themesberg.com" target="_blank">Themesberg</a>
                - Coded by <a href="https://appseed.us" target="_blank">AppSeed</a>.
            </p>
        </div>
        <div class="col-12 col-md-8 col-xl-6 text-center text-lg-start">
            <!-- List -->
            <ul class="list-inline list-group-flush list-group-borderless text-md-end mb-0">
                <li class="list-inline-item px-0 px-sm-2">
                    <a target="_blank" 
                       href="https://appseed.us/admin-dashboards/django-dashboard-volt">Django Volt Dashboard</a>
                </li>
            </ul>
        </div>
    </div>
</footer>

worldpostcodes/templates/includes/navigation.html
<nav class="navbar navbar-top navbar-expand navbar-dashboard navbar-dark ps-0 pe-2 pb-0">
              <div class="container-fluid px-0">
                <div class="d-flex justify-content-between w-100" id="navbarSupportedContent">
                  <div class="d-flex align-items-center">

                  </div>
                  <!-- Navbar links -->
                  <ul class="navbar-nav align-items-center">
                    <li class="nav-item dropdown ms-lg-3">
                      <a class="nav-link dropdown-toggle pt-1 px-0" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        <div class="media d-flex align-items-center">
                          <img class="avatar rounded-circle" alt="Image placeholder" src="/static/volt/assets/img/team/profile-picture-3.jpg">
                          <div class="media-body ms-2 text-dark align-items-center d-none d-lg-block">
                            <span class="mb-0 font-small fw-bold text-gray-900">
                              Current User: <strong>{{ request.user.email }}</strong>
                            </span>
                          </div>
                        </div>
                      </a>
                      <div class="dropdown-menu dashboard-dropdown dropdown-menu-end mt-2 py-1">
                        <a class="dropdown-item d-flex align-items-center" href="/settings.html">
                          <svg class="dropdown-icon text-gray-400 me-2" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-6-3a2 2 0 11-4 0 2 2 0 014 0zm-2 4a5 5 0 00-4.546 2.916A5.986 5.986 0 0010 16a5.986 5.986 0 004.546-2.084A5 5 0 0010 11z" clip-rule="evenodd"></path></svg>
                          My Profile
                        </a>
                        <div role="separator" class="dropdown-divider my-1"></div>

                        <div class="dropdown-item d-flex align-items-center" >
                          <svg class="dropdown-icon text-danger me-2" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M17 16l4-4m0 0l-4-4m4 4H7m6 4v1a3 3 0 01-3 3H6a3 3 0 01-3-3V7a3 3 0 013-3h4a3 3 0 013 3v1"></path></svg>                
                          <form action="{% url 'logout' %}" method="post">{% csrf_token %} <input type="submit" value="Logout"></form>
                        </div>
                      </div>
                    </li>
                  </ul>
                </div>
              </div>
            </nav>

worldpostcodes/templates/includes/scripts.html
<!-- Core -->
<script src="/static/volt/assets/vendor/@popperjs/core/dist/umd/popper.min.js"></script>
<script src="/static/volt/assets/vendor/bootstrap/dist/js/bootstrap.min.js"></script>

<!-- Vendor JS -->
<script src="/static/volt/assets/vendor/onscreen/dist/on-screen.umd.min.js"></script>

<!-- Slider -->
<script src="/static/volt/assets/vendor/nouislider/distribute/nouislider.min.js"></script>

<!-- Smooth scroll -->
<script src="/static/volt/assets/vendor/smooth-scroll/dist/smooth-scroll.polyfills.min.js"></script>

<!-- Charts -->
<script src="/static/volt/assets/vendor/chartist/dist/chartist.min.js"></script>
<script src="/static/volt/assets/vendor/chartist-plugin-tooltips/dist/chartist-plugin-tooltip.min.js"></script>

<!-- Datepicker -->
<script src="/static/volt/assets/vendor/vanillajs-datepicker/dist/js/datepicker.min.js"></script>

<!-- Sweet Alerts 2 -->
<script src="/static/volt/assets/vendor/sweetalert2/dist/sweetalert2.all.min.js"></script>

<!-- Moment JS -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.27.0/moment.min.js"></script>

<!-- Vanilla JS Datepicker -->
<script src="/static/volt/assets/vendor/vanillajs-datepicker/dist/js/datepicker.min.js"></script>

<!-- Notyf -->
<script src="/static/volt/assets/vendor/notyf/notyf.min.js"></script>

<!-- Simplebar -->
<script src="/static/volt/assets/vendor/simplebar/dist/simplebar.min.js"></script>

<!-- Github buttons -->
<script async defer src="https://buttons.github.io/buttons.js"></script>



<!-- Volt JS -->
<script src="/static/volt/assets/js/volt.js"></script>

worldpostcodes/templates/includes/settings-box.html
    <div class="theme-settings card bg-gray-800 pt-2 collapse" id="theme-settings">
        <div class="card-body bg-gray-800 text-white pt-4">
            <button type="button" class="btn-close theme-settings-close" aria-label="Close" data-bs-toggle="collapse"
                href="#theme-settings" role="button" aria-expanded="false" aria-controls="theme-settings"></button>
            <div class="d-flex justify-content-between align-items-center mb-3">
                <p class="m-0 mb-1 me-4 fs-7">Open source <span role="img" aria-label="gratitude">💛</span></p>
                <a class="github-button" href="https://github.com/themesberg/volt-bootstrap-5-dashboard"
                    data-color-scheme="no-preference: dark; light: light; dark: light;" data-icon="octicon-star"
                    data-size="large" data-show-count="true"
                    aria-label="Star themesberg/volt-bootstrap-5-dashboard on GitHub">Star</a>
            </div>
            <a href="https://themesberg.com/product/admin-dashboard/volt-bootstrap-5-dashboard" target="_blank"
                class="btn btn-secondary d-inline-flex align-items-center justify-content-center mb-3 w-100">
                Download 
                <svg class="icon icon-xs ms-2" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M2 9.5A3.5 3.5 0 005.5 13H9v2.586l-1.293-1.293a1 1 0 00-1.414 1.414l3 3a1 1 0 001.414 0l3-3a1 1 0 00-1.414-1.414L11 15.586V13h2.5a4.5 4.5 0 10-.616-8.958 4.002 4.002 0 10-7.753 1.977A3.5 3.5 0 002 9.5zm9 3.5H9V8a1 1 0 012 0v5z" clip-rule="evenodd"></path></svg>
            </a>
            <p class="fs-7 text-gray-300 text-center">Available in the following technologies:</p>
            <div class="d-flex justify-content-center">
                <a class="me-3" href="https://themesberg.com/product/admin-dashboard/volt-bootstrap-5-dashboard"
                    target="_blank">
                    <img src="/static/volt/assets/img/technologies/bootstrap-5-logo.svg" class="image image-xs">
                </a>
                <a href="https://demo.themesberg.com/volt-react-dashboard/#/" target="_blank">
                    <img src="/static/volt/assets/img/technologies/react-logo.svg" class="image image-xs">
                </a>
            </div>
        </div>
    </div>

    <div class="card theme-settings bg-gray-800 theme-settings-expand" id="theme-settings-expand">
        <div class="card-body bg-gray-800 text-white rounded-top p-3 py-2">
            <span class="fw-bold d-inline-flex align-items-center h6">
                <svg class="icon icon-xs me-2" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M11.49 3.17c-.38-1.56-2.6-1.56-2.98 0a1.532 1.532 0 01-2.286.948c-1.372-.836-2.942.734-2.106 2.106.54.886.061 2.042-.947 2.287-1.561.379-1.561 2.6 0 2.978a1.532 1.532 0 01.947 2.287c-.836 1.372.734 2.942 2.106 2.106a1.532 1.532 0 012.287.947c.379 1.561 2.6 1.561 2.978 0a1.533 1.533 0 012.287-.947c1.372.836 2.942-.734 2.106-2.106a1.533 1.533 0 01.947-2.287c1.561-.379 1.561-2.6 0-2.978a1.532 1.532 0 01-.947-2.287c.836-1.372-.734-2.942-2.106-2.106a1.532 1.532 0 01-2.287-.947zM10 13a3 3 0 100-6 3 3 0 000 6z" clip-rule="evenodd"></path></svg>
                Settings
            </span>
        </div>
    </div>

worldpostcodes/templates/includes/sidebar.html
        <nav class="navbar navbar-dark navbar-theme-primary px-4 col-12 d-lg-none">
            <a class="navbar-brand me-lg-5" href="/">
                <img class="navbar-brand-dark" src="/static/volt/assets/img/brand/light.svg" alt="Volt logo" /> <img class="navbar-brand-light" src="/static/volt/assets/img/brand/dark.svg" alt="Volt logo" />
            </a>
            <div class="d-flex align-items-center">
                <button class="navbar-toggler d-lg-none collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#sidebarMenu" aria-controls="sidebarMenu" aria-expanded="false" aria-label="Toggle navigation">
                  <span class="navbar-toggler-icon"></span>
                </button>
            </div>
        </nav>

        <nav id="sidebarMenu" class="sidebar d-lg-block bg-gray-800 text-white collapse" data-simplebar>
          <div class="sidebar-inner px-4 pt-3">
            <div class="user-card d-flex d-md-none align-items-center justify-content-between justify-content-md-center pb-4">
              <div class="d-flex align-items-center">
                <div class="avatar-lg me-4">
                  <img src="/static/volt/assets/img/team/profile-picture-3.jpg" class="card-img-top rounded-circle border-white"
                    alt="Bonnie Green">
                </div>
                <div class="d-block">
                  <h2 class="h5 mb-3">Hi, Jane</h2>
                  <a href="/page-sign-in.html" class="btn btn-secondary btn-sm d-inline-flex align-items-center">
                    <svg class="icon icon-xxs me-1" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M17 16l4-4m0 0l-4-4m4 4H7m6 4v1a3 3 0 01-3 3H6a3 3 0 01-3-3V7a3 3 0 013-3h4a3 3 0 013 3v1"></path></svg>            
                    Sign Out
                  </a>
                </div>
              </div>
              <div class="collapse-close d-md-none">
                <a href="#sidebarMenu" data-bs-toggle="collapse"
                    data-bs-target="#sidebarMenu" aria-controls="sidebarMenu" aria-expanded="true"
                    aria-label="Toggle navigation">
                    <svg class="icon icon-xs" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z" clip-rule="evenodd"></path></svg>
                  </a>
              </div>
            </div>
            <ul class="nav flex-column pt-3 pt-md-0">
              <li class="nav-item">
                <a href="/" class="nav-link d-flex align-items-center">
                  <span class="sidebar-icon">
                    <img src="/static/volt/assets/img/brand/light.svg" height="20" width="20" alt="Volt Logo">
                  </span>
                  <span class="mt-1 ms-1 sidebar-text">Volt Overview</span>
                </a>
              </li>
              <li class="nav-item {% if 'dashboard' in segment %} active {% endif %}">
                <a href="{% url 'index' %}" class="nav-link">
                  <span class="sidebar-icon">
                    <svg class="icon icon-xs me-2" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path d="M2 10a8 8 0 018-8v8h8a8 8 0 11-16 0z"></path><path d="M12 2.252A8.014 8.014 0 0117.748 8H12V2.252z"></path></svg>
                  </span> 
                  <span class="sidebar-text">Dashboard</span>
                </a>
              </li>
              <li class="nav-item {% if 'tables-bootstrap-' in segment %} active {% endif %}">
                <span
                  class="nav-link  collapsed  d-flex justify-content-between align-items-center"
                  data-bs-toggle="collapse" data-bs-target="#submenu-app">
                  <span>
                    <span class="sidebar-icon">
                      <svg class="icon icon-xs me-2" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M5 4a3 3 0 00-3 3v6a3 3 0 003 3h10a3 3 0 003-3V7a3 3 0 00-3-3H5zm-1 9v-1h5v2H5a1 1 0 01-1-1zm7 1h4a1 1 0 001-1v-1h-5v2zm0-4h5V8h-5v2zM9 8H4v2h5V8z" clip-rule="evenodd"></path></svg>
                    </span> 
                    <span class="sidebar-text">Companies</span>
                  </span>
                  <span class="link-arrow">
                    <svg class="icon icon-sm" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M7.293 14.707a1 1 0 010-1.414L10.586 10 7.293 6.707a1 1 0 011.414-1.414l4 4a1 1 0 010 1.414l-4 4a1 1 0 01-1.414 0z" clip-rule="evenodd"></path></svg>
                  </span>
                </span>
                <div class="multi-level collapse {% if 'tables-bootstrap-' in segment %} show {% endif %}"
                  role="list" id="submenu-app" aria-expanded="false">
                  <ul class="flex-column nav">
                    <li class="nav-item {% if 'bootstrap-tables' in segment %} active {% endif %}">
                      <a class="nav-link" href="{% url 'companies:company_list' %}">
                        <span class="sidebar-text">Companies</span>
                      </a>
                    </li>
                  </ul>
                </div>
              </li>
              <li class="nav-item {% if 'page-' in segment %} active {% endif %}">
                <span
                  class="nav-link  collapsed  d-flex justify-content-between align-items-center"
                  data-bs-toggle="collapse" data-bs-target="#submenu-pages">
                  <span>
                    <span class="sidebar-icon">
                      <svg class="icon icon-xs me-2" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M2 5a2 2 0 012-2h8a2 2 0 012 2v10a2 2 0 002 2H4a2 2 0 01-2-2V5zm3 1h6v4H5V6zm6 6H5v2h6v-2z" clip-rule="evenodd"></path><path d="M15 7h1a2 2 0 012 2v5.5a1.5 1.5 0 01-3 0V7z"></path></svg>
                    </span> 
                    <span class="sidebar-text">Invitations</span>
                  </span>
                  <span class="link-arrow">
                    <svg class="icon icon-sm" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M7.293 14.707a1 1 0 010-1.414L10.586 10 7.293 6.707a1 1 0 011.414-1.414l4 4a1 1 0 010 1.414l-4 4a1 1 0 01-1.414 0z" clip-rule="evenodd"></path></svg>
                  </span>
                </span>
                <div class="multi-level collapse {% if 'page-' in segment %} show {% endif %} " role="list"
                  id="submenu-pages" aria-expanded="false">
                  <ul class="flex-column nav">
                    <li class="nav-item">
                      <a class="nav-link" href="{% url 'invitations:invitation_list' %}">
                        <span class="sidebar-text">Invitations</span>
                      </a>
                    </li>
                  </ul>
                </div>
              </li>
               <li role="separator" class="dropdown-divider mt-4 mb-3 border-gray-700"></li>
              <li class="nav-item">
                <a href="https://appseed.us/admin-dashboards/django-dashboard-volt" target="_blank"
                  class="nav-link d-flex align-items-center">
                  <span class="sidebar-icon">
                    <svg class="icon icon-xs me-2" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-8-3a1 1 0 00-.867.5 1 1 0 11-1.731-1A3 3 0 0113 8a3.001 3.001 0 01-2 2.83V11a1 1 0 11-2 0v-1a1 1 0 011-1 1 1 0 100-2zm0 8a1 1 0 100-2 1 1 0 000 2z" clip-rule="evenodd"></path></svg>
                  </span>
                  <span class="sidebar-text">Product Page</span>
                </a>
              </li>
            </ul>
          </div>
        </nav>